apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: mysql
        image:  mysql:latest
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app    ## Corresponde al nombre asignado en el configmap
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: app
              key: MYSQL_USER
        - name: MYSQL_RAMDON_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app
              key: MYSQL_RAMDON_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app
              key: MYSQL_PASSWORD
        ports:
        - containerPort:  80
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
      # restartPolicy: Always