apiVersion: v1
kind: Service
metadata:
  name: mysql   ## DNS - cluster interno
  labels:
    app: db 
spec:
  selector:
    app: db     ## para buscar el deployment que tenga ese label 
  type: ClusterIP
  ports:        ## estos serian los puertos que va a escuchar
  - name: http
    port: 3306
    targetPort: 3306
  - name: mysql
    port: 33060
    targetPort: 33060